# Generated by Django 5.1.1 on 2024-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattable',
            name='time_stamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
